version: '3.8'

services:
  db:
    image: mariadb:12
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fundtransfert
      MYSQL_USER: funduser
      MYSQL_PASSWORD: fundpass
    ports:
      - "13306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
